from typing import Any

from app.capabilities._base import Capability
from app.capabilities._schemas.models import CapabilityResult, Card, RunContext


class BrainExtractCapability(Capability):
    async def invoke(self, context: RunContext, input_data: dict[str, Any]) -> CapabilityResult:
        # Stub implementation for brain_extract
        card = Card(kind="brain_extract", data={"message": "Generated by brain_extract capability"})
        return CapabilityResult(cards=[card], assets=[{"kind": "brain_extract", "content": card.data}])
