from typing import Any

from app.capabilities._base import Capability
from app.capabilities._schemas.models import CapabilityResult, Card, RunContext


class CommentAnalyzerCapability(Capability):
    async def invoke(self, context: RunContext, input_data: dict[str, Any]) -> CapabilityResult:
        # Stub implementation for comment_analyzer
        card = Card(kind="comment_analyzer", data={"message": "Generated by comment_analyzer capability"})
        return CapabilityResult(cards=[card], assets=[{"kind": "comment_analyzer", "content": card.data}])
