from typing import Any

from app.capabilities._base import Capability
from app.capabilities._schemas.models import CapabilityResult, Card, RunContext


class InsightExtractorCapability(Capability):
    async def invoke(self, context: RunContext, input_data: dict[str, Any]) -> CapabilityResult:
        # Stub implementation for insight_extractor
        card = Card(kind="insight_extractor", data={"message": "Generated by insight_extractor capability"})
        return CapabilityResult(cards=[card], assets=[{"kind": "insight_extractor", "content": card.data}])
