from typing import Any

from app.capabilities._base import Capability
from app.capabilities._schemas.models import CapabilityResult, Card, RunContext


class OpportunityFinderCapability(Capability):
    async def invoke(self, context: RunContext, input_data: dict[str, Any]) -> CapabilityResult:
        # Stub implementation for opportunity_finder
        card = Card(kind="opportunity_finder", data={"message": "Generated by opportunity_finder capability"})
        return CapabilityResult(cards=[card], assets=[{"kind": "opportunity_finder", "content": card.data}])
