from typing import Any

from app.capabilities._base import Capability
from app.capabilities._schemas.models import CapabilityResult, Card, RunContext


class OutlineCapability(Capability):
    async def invoke(self, context: RunContext, input_data: dict[str, Any]) -> CapabilityResult:
        # Stub implementation for outline
        card = Card(kind="outline", data={"message": "Generated by outline capability"})
        return CapabilityResult(cards=[card], assets=[{"kind": "outline", "content": card.data}])
