from typing import Any

from app.capabilities._base import Capability
from app.capabilities._schemas.models import CapabilityResult, Card, RunContext


class PitchWriterCapability(Capability):
    async def invoke(self, context: RunContext, input_data: dict[str, Any]) -> CapabilityResult:
        # Stub implementation for pitch_writer
        card = Card(kind="pitch_writer", data={"message": "Generated by pitch_writer capability"})
        return CapabilityResult(cards=[card], assets=[{"kind": "pitch_writer", "content": card.data}])
