from typing import Any

from app.capabilities._base import Capability
from app.capabilities._schemas.models import CapabilityResult, Card, RunContext


class PlatformAdaptCapability(Capability):
    async def invoke(self, context: RunContext, input_data: dict[str, Any]) -> CapabilityResult:
        # Stub implementation for platform_adapt
        card = Card(kind="platform_adapt", data={"message": "Generated by platform_adapt capability"})
        return CapabilityResult(cards=[card], assets=[{"kind": "platform_adapt", "content": card.data}])
