from typing import Any

from app.capabilities._base import Capability
from app.capabilities._schemas.models import CapabilityResult, Card, RunContext


class RepurposeCapability(Capability):
    async def invoke(self, context: RunContext, input_data: dict[str, Any]) -> CapabilityResult:
        # Stub implementation for repurpose
        card = Card(kind="repurpose", data={"message": "Generated by repurpose capability"})
        return CapabilityResult(cards=[card], assets=[{"kind": "repurpose", "content": card.data}])
