from typing import Any

from app.capabilities._base import Capability
from app.capabilities._schemas.models import CapabilityResult, Card, RunContext


class RewriteCapability(Capability):
    async def invoke(self, context: RunContext, input_data: dict[str, Any]) -> CapabilityResult:
        # Stub implementation for rewrite
        card = Card(kind="rewrite", data={"message": "Generated by rewrite capability"})
        return CapabilityResult(cards=[card], assets=[{"kind": "rewrite", "content": card.data}])
