from typing import Any

from app.capabilities._base import Capability
from app.capabilities._schemas.models import CapabilityResult, Card, RunContext


class TrendAnalysisCapability(Capability):
    async def invoke(self, context: RunContext, input_data: dict[str, Any]) -> CapabilityResult:
        # Stub implementation for trend_analysis
        card = Card(kind="trend_analysis", data={"message": "Generated by trend_analysis capability"})
        return CapabilityResult(cards=[card], assets=[{"kind": "trend_analysis", "content": card.data}])
