import type {TResult,TConcept} from "./schema";
const mk=(name:string,strategy:string,text:string,place:string,bg:string,why:string,vis:string):TConcept=>({name,strategy,visualDirection:vis,creatorPlacement:"Centered, chest-up",facialExpression:"Natural, relaxed",background:bg,supportingVisuals:"None needed",text,textPlacement:place,composition:"Subject fills the middle third so it survives the grid crop",aesthetic:"Warm, soft light",whyItWorks:why});
export function fallback(desc:string,type:string):TResult{
 const d=(desc+" "+type).toLowerCase();
 if(/battery|tech|phone|code|educ/.test(d)) return {analysis:{contentType:type,visualHook:"The problem, stated instantly",emotionalHook:"Curiosity",creatorImportance:"low",recommendedStrategy:"TEXT_FIRST",textLevel:"HEADLINE",reason:"Educational content needs context at a glance, so a short headline does the work."},concepts:[mk("The Question","TEXT_FIRST","Why your battery dies","top","Clean pearl background","A direct question tells viewers exactly what they'll learn.","Big headline with a simple battery graphic"),mk("Creator + Fix","HYBRID","Fix it in 2 min","bottom","Deep teal","Face builds trust while the text promises a quick answer.","Creator pointing at a settings screen"),mk("Screenshot Proof","HYBRID","Battery settings","top","Dark neutral","Showing the real screen sets honest expectations.","Phone screen mockup with creator corner")]};
 if(/paint|art|draw|sketch/.test(d)) return {analysis:{contentType:type,visualHook:"The artwork itself",emotionalHook:"Awe",creatorImportance:"low",recommendedStrategy:"VISUAL_FIRST",textLevel:"NONE",reason:"The finished piece is the hook. Text would only cover it."},concepts:[mk("The Detail","VISUAL_FIRST","","none","Dark, artwork-lit","Close detail makes people stop scrolling.","Extreme close-up of the finished eye"),mk("Halfway There","COMPARISON","","none","Blank canvas vs finished","Contrast hints at the transformation.","Split: blank canvas and finished piece"),mk("Artist at Work","MINIMAL","","none","Studio warm light","Personal and quiet, fits the grid.","Hands mid-brushstroke")]};
 if(/clean|before|after|transform/.test(d)) return {analysis:{contentType:type,visualHook:"The before and after",emotionalHook:"Satisfaction",creatorImportance:"low",recommendedStrategy:"COMPARISON",textLevel:"MINIMAL",reason:"The transformation sells itself. One or two words at most."},concepts:[mk("Split Room","COMPARISON","Before / After","bottom","Split messy vs clean","Contrast is instantly readable.","Vertical split of the same angle"),mk("Clean Result","VISUAL_FIRST","","none","Tidy bright room","The finished room is satisfying alone.","Wide shot of the finished room"),mk("Mid-Chaos","STORY_MOMENT","Day 1","top","Messy room","Curiosity about how it ends.","Creator in the middle of the mess")]};
 if(/story|embarrass/.test(d)) return {analysis:{contentType:type,visualHook:"A reaction that hints at the story",emotionalHook:"Cringe and curiosity",creatorImportance:"high",recommendedStrategy:"STORY_MOMENT",textLevel:"MINIMAL",reason:"Your expression carries the story better than a headline would."},concepts:[mk("The Cringe","STORY_MOMENT","","none","Soft neutral","A real reaction invites the click.","Close-up of a wincing face, half-done makeup"),mk("Tell You Later","FACE_FIRST","Storytime","bottom","Warm blush","Short label sets the format.","Creator looking at camera mid-makeup"),mk("Half Done","FACE_FIRST","","none","Vanity mirror light","Half a face says story in progress.","Half-done look, eyebrow raised")]};
 if(/makeup|beauty/.test(d)) return {analysis:{contentType:type,visualHook:"The finished look",emotionalHook:"Confidence",creatorImportance:"high",recommendedStrategy:"VISUAL_FIRST",textLevel:"MINIMAL",reason:"The result and your face together beat any headline."},concepts:[mk("The Glow","VISUAL_FIRST","","none","Soft blush","Close crop shows the result.","Close-up of the finished eye and cheek"),mk("Five Products","HYBRID","5 products","bottom","Neutral cream","Number gives a clear promise.","Face with the five products in a row"),mk("Mirror Moment","FACE_FIRST","","none","Warm vanity light","Authentic and grid-friendly.","Creator glancing at mirror")]};
 return {analysis:{contentType:type,visualHook:"Creator presence and mood",emotionalHook:"Relatability",creatorImportance:"high",recommendedStrategy:"FACE_FIRST",textLevel:"NONE",reason:"Your face and mood are the strongest hook. Text would add clutter."},concepts:[mk("Golden Hour You","FACE_FIRST","","none","Warm outdoor light","Feels real, not staged.","Candid portrait, soft light"),mk("Coffee Run","MINIMAL","day in my life","bottom","Cafe tones","Tiny label sets context without clickbait.","Creator with coffee, off-center"),mk("Getting Ready","FACE_FIRST","","none","Bedroom mirror","Personal and consistent with the grid.","Mirror shot, natural expression")]};
}
