"""add body to generated_drafts

Revision ID: 90e10a69c6b1
Revises: e71b93f2810a
Create Date: 2026-09-30 00:19:06.232972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e10a69c6b1'
down_revision: Union[str, Sequence[str], None] = 'e71b93f2810a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_drafts', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_drafts', 'body')
    # ### end Alembic commands ###
