"""Add analysis_status and errors to posts

Revision ID: cd52d08bc5b8
Revises: 001_initial_schema
Create Date: 2026-09-29 13:06:33.922365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd52d08bc5b8'
down_revision: Union[str, Sequence[str], None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('analysis_status', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('analysis_error', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('parse_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'parse_error')
    op.drop_column('posts', 'analysis_error')
    op.drop_column('posts', 'analysis_status')
    # ### end Alembic commands ###
