import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const checkFile = path.resolve(__dirname, '../docs/checkpoints.md');

let content = fs.readFileSync(checkFile, 'utf8');

const stages = [
  { wave: 'W0', num: 0 },
  { wave: 'W1', num: 1 },
  { wave: 'W1', num: 2 },
  { wave: 'W1', num: 4 },
  { wave: 'W2', num: 3 },
  { wave: 'W2', num: 5 },
  { wave: 'W2', num: 6 },
  { wave: 'W3', num: 7 },
  { wave: 'W3', num: 8 },
  { wave: 'W3', num: 9 },
  { wave: 'W4', num: 10 },
  { wave: '—', num: 11, deferred: true },
];

let overallDone = 0;
let overallTotal = 0;
const waveStats = {};
const stageStats = {};

stages.forEach(s => {
  if (!waveStats[s.wave]) {
    waveStats[s.wave] = { done: 0, total: 0, stages: [] };
  }
  waveStats[s.wave].stages.push(s.num);
});

// find stage sections
for (const stage of stages) {
  const regex = new RegExp(`## Stage ${stage.num} —[\\s\\S]*?(?=## Stage|$)`);
  const match = content.match(regex);
  if (match) {
    const section = match[0];
    const checkboxes = section.match(/- \[(x| )\]/g) || [];
    const done = checkboxes.filter(c => c === '- [x]').length;
    const total = checkboxes.length;
    
    stageStats[stage.num] = { done, total, pct: total ? Math.round((done/total)*100) : 0 };
    
    if (!stage.deferred) {
      overallDone += done;
      overallTotal += total;
    }
    
    waveStats[stage.wave].done += done;
    waveStats[stage.wave].total += total;

    // Replace the stage stats in the table in "## Stage status"
    // Wait, the prompt says "rewrites the header block ... in place." 
    // And for the Stage status table, we can just replace the whole table or let's just stick to the header block.
    // Ah, wait: "The script parses ... computes per-stage and overall percentages, and rewrites the header block ... in place."
  }
}

const overallPct = overallTotal ? Math.round((overallDone / overallTotal) * 100) : 0;
const filledLen = Math.round(overallPct / 2);
const bar = '[' + '-'.repeat(filledLen) + ' '.repeat(50 - filledLen) + ']';

const headerStart = '<!-- CHECKPOINTS:HEADER:START — regenerated by `pnpm checkpoints`. Do not edit by hand. -->';
const headerEnd = '<!-- CHECKPOINTS:HEADER:END -->';

const newHeaderLines = [
  headerStart,
  '',
  `**Overall: ${overallPct}% complete** — ${overallDone} / ${overallTotal} checkpoints`,
  '',
  '```',
  `${bar}   ${overallPct}%`,
  '```',
  '',
  '| Wave | Stages | Done | Total | % |',
  '|---|---|---|---|---|'
];

for (const [wave, stats] of Object.entries(waveStats)) {
  const pct = stats.total ? Math.round((stats.done / stats.total) * 100) : 0;
  const stageList = stats.stages.join(' · ');
  const deferredText = wave === '—' ? ' *(deferred)*' : '';
  newHeaderLines.push(`| ${wave} | ${stageList}${deferredText} | ${stats.done} | ${stats.total} | ${pct}% |`);
}

newHeaderLines.push(
  '',
  '*Stage 11 is excluded from the overall total until Meta App Review is approved.*',
  '',
  headerEnd
);

const newHeader = newHeaderLines.join('\\n');
content = content.replace(new RegExp(`${headerStart}[\\s\\S]*?${headerEnd}`), newHeader);

// Update Stage Status table? 
// The prompt also says: "computes per-stage ... and rewrites the header block"
// It's safer to only rewrite the header. But let's also update the stage table if needed.
// "and rewrites the header block (overall %, ASCII progress bar, per-wave roll-up) in place."
// Okay, let's just rewrite the header.

fs.writeFileSync(checkFile, content, 'utf8');
