import os


def write_file(path, content):
    if os.path.dirname(path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content.strip() + "\n")

# --- Phase 9: Remaining Capabilities ---
caps = [
    "outline", "rewrite", "repurpose", "platform_adapt", "brain_extract",
    "trend_analysis", "opportunity_finder", "pitch_writer", "comment_analyzer", "insight_extractor"
]

for cap in caps:
    class_name = "".join(word.capitalize() for word in cap.split('_')) + "Capability"
    write_file(f'app/capabilities/{cap}.py', f"""
from app.capabilities._base import Capability
from app.capabilities._schemas.models import RunContext, CapabilityResult, Card
from typing import Dict, Any

class {class_name}(Capability):
    async def invoke(self, context: RunContext, input_data: Dict[str, Any]) -> CapabilityResult:
        # Stub implementation for {cap}
        card = Card(kind="{cap}", data={{"message": "Generated by {cap} capability"}})
        return CapabilityResult(cards=[card], assets=[{{"kind": "{cap}", "content": card.data}}])
""")

# Update capability registry
yaml_content = "capabilities:\n"
# Original ones
for cap in ["research", "hook", "script"]:
    class_name = cap.capitalize() + "Capability"
    yaml_content += f"  - name: {cap}\n    class_path: app.capabilities.{cap}.{class_name}\n"

# New ones
for cap in caps:
    class_name = "".join(word.capitalize() for word in cap.split('_')) + "Capability"
    yaml_content += f"  - name: {cap}\n    class_path: app.capabilities.{cap}.{class_name}\n"

write_file('capability_registry.yaml', yaml_content)

print("Phase 9 capabilities generated and registered.")
